version: "3.7"

services:
    app:
        build:
            args:
                user: pure
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/logs:/var/log/:rw
            - ./docker-compose/logs/laravel:/var/www/storage/logs/:rw
        networks:
            - internal

    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        ports:
            - 8000:${DB_PORT}
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./tmp/db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - internal

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www:rw
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./storage/app/public:/var/www/public/storage:rw
            - ./docker-compose/certbot/www:/var/www/certbot/:ro
            - ./docker-compose/certbot/conf/:/etc/nginx/ssl/:ro
            - ./docker-compose/logs/nginx/:/var/log/nginx/:rw
        networks:
            - internal

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./docker-compose/certbot/www/:/var/www/certbot/:rw
            - ./docker-compose/certbot/conf/:/etc/letsencrypt/:rw
            - ./docker-compose/logs:/var/log/:rw
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.220.0/28
