version: "3.7"

services:
    app:
        build:
            args:
                user: pure
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./tmp/db:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/

